export const MOCK_CARS = [
  {
    id: 1, slug: 'mercedes-benz-gle-2022',
    title: 'Mercedes-Benz GLE 350 2022',
    brand: { name: 'Mercedes-Benz' },
    category: 'Tokunbo',
    price: '68000000',
    mileage: 28000,
    year: 2022,
    transmission: 'Automatic',
    engine_size: '2.0L Turbo',
    status: 'Available',
    badge: 'Premium',
    description: 'Immaculate condition. Full leather interior, panoramic roof, 360 camera, ambient lighting. Accident free.',
    features: ['Panoramic Roof', 'Burmester Sound', '360 Camera', 'Ambient Lighting', 'Heated Seats', 'Head-up Display'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 2, slug: 'toyota-land-cruiser-2021',
    title: 'Toyota Land Cruiser V8 2021',
    brand: { name: 'Toyota' },
    category: 'Tokunbo',
    price: '95000000',
    mileage: 35000,
    year: 2021,
    transmission: 'Automatic',
    engine_size: '4.6L V8',
    status: 'Available',
    badge: 'Hot Bid',
    description: 'The king of SUVs. Full option with third row seating, crawl control, and multi-terrain select.',
    features: ['4WD', 'Third Row', 'Crawl Control', 'Kinetic Dynamic Suspension', 'JBL Sound', 'Power Tailgate'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 3, slug: 'lexus-lx-570-2020',
    title: 'Lexus LX 570 Sport 2020',
    brand: { name: 'Lexus' },
    category: 'Tokunbo',
    price: '85000000',
    mileage: 42000,
    year: 2020,
    transmission: 'Automatic',
    engine_size: '5.7L V8',
    status: 'Available',
    badge: 'New',
    description: 'Sport edition with black exterior package. Ultra-luxury Japanese engineering at its finest.',
    features: ['Sport Package', 'Mark Levinson Audio', 'Night Vision', 'Cooled & Heated Seats', 'Rear Entertainment'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 4, slug: 'porsche-cayenne-2021',
    title: 'Porsche Cayenne S 2021',
    brand: { name: 'Porsche' },
    category: 'Tokunbo',
    price: '72000000',
    mileage: 19000,
    year: 2021,
    transmission: 'Automatic',
    engine_size: '2.9L Turbo V6',
    status: 'Available',
    badge: 'Premium',
    description: 'Cayenne S with Sport Chrono package. PASM suspension. Bose surround sound.',
    features: ['Sport Chrono', 'PASM Suspension', 'Bose Sound', 'Panoramic Roof', 'Air Suspension', '21" Wheels'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 5, slug: 'bmw-x6-2022',
    title: 'BMW X6 M50i 2022',
    brand: { name: 'BMW' },
    category: 'Foreign Used',
    price: '58000000',
    mileage: 22000,
    year: 2022,
    transmission: 'Automatic',
    engine_size: '4.4L V8',
    status: 'Available',
    badge: 'Hot Bid',
    description: 'M50i Performance package. Iconic fastback SUV with 523hp twin-turbo V8.',
    features: ['M Sport Package', 'Harman Kardon', 'Laser Headlights', 'Gesture Control', 'Driving Assistant Pro'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 6, slug: 'toyota-camry-2023',
    title: 'Toyota Camry XSE 2023',
    brand: { name: 'Toyota' },
    category: 'Brand New',
    price: '28000000',
    mileage: 0,
    year: 2023,
    transmission: 'Automatic',
    engine_size: '2.5L',
    status: 'Available',
    badge: 'New',
    description: 'Zero mileage. Brand new from dealer. Sport Edition with red interior.',
    features: ['Brand New', 'Sport Edition', 'Red Interior', 'Apple CarPlay', 'Toyota Safety Sense', 'LED Headlights'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 7, slug: 'range-rover-autobiography-2021',
    title: 'Range Rover Autobiography 2021',
    brand: { name: 'Range Rover' },
    category: 'Tokunbo',
    price: '125000000',
    mileage: 31000,
    year: 2021,
    transmission: 'Automatic',
    engine_size: '5.0L V8',
    status: 'Available',
    badge: 'Premium',
    description: 'Long Wheelbase Autobiography. The pinnacle of luxury SUVs. Full option.',
    features: ['Long Wheelbase', 'Executive Seats', 'Rear Suite', 'Meridian Sound', 'Terrain Response 2', 'Pixel LED'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
  {
    id: 8, slug: 'honda-accord-2022',
    title: 'Honda Accord Sport 2022',
    brand: { name: 'Honda' },
    category: 'Nigerian Used',
    price: '16500000',
    mileage: 48000,
    year: 2022,
    transmission: 'Automatic',
    engine_size: '1.5L Turbo',
    status: 'Sold',
    badge: null,
    description: 'Well maintained. Honda Sensing safety suite. Cloth sport interior.',
    features: ['Honda Sensing', 'Apple CarPlay', 'Android Auto', 'Wireless Charging', 'Heated Seats'],
    whatsapp_link: 'https://wa.me/2348000000000',
    images: [{ image: null, is_primary: true }],
  },
]

export const MOCK_BRANDS = [
  { id: 1, name: 'Toyota' },
  { id: 2, name: 'Mercedes-Benz' },
  { id: 3, name: 'Lexus' },
  { id: 4, name: 'BMW' },
  { id: 5, name: 'Honda' },
  { id: 6, name: 'Porsche' },
  { id: 7, name: 'Range Rover' },
  { id: 8, name: 'Audi' },
]

export const MOCK_POSTS = [
  {
    id: 1, slug: 'tokunbo-vs-nigerian-used',
    title: "Tokunbo vs Nigerian Used: The Complete Buyer's Guide for 2025",
    excerpt: 'Every Nigerian car buyer faces this question. We break it down so you can make the smartest decision for your budget.',
    category: { name: 'Buyer\'s Guide' },
    published_at: '2025-03-01',
    views: 4820,
    thumbnail: null,
  },
  {
    id: 2, slug: 'why-car-prices-rising',
    title: 'Why Car Prices Keep Rising in Nigeria — And When They Will Drop',
    excerpt: 'Forex, customs duties, demand. We analyse the exact forces pushing Nigerian car prices higher and what savvy buyers can do.',
    category: { name: 'Market Watch' },
    published_at: '2025-02-15',
    views: 6310,
    thumbnail: null,
  },
  {
    id: 3, slug: 'luxury-suvs-nigeria-2025',
    title: 'Top 7 Luxury SUVs Under ₦80M You Can Buy in Nigeria Right Now',
    excerpt: 'Premium doesn\'t have to break the bank. These seven SUVs deliver world-class luxury at the most competitive prices in the market.',
    category: { name: 'Reviews' },
    published_at: '2025-01-28',
    views: 9140,
    thumbnail: null,
  },
]

export const MOCK_STATS = {
  total_listings: 47,
  sold_count: 312,
  brands_count: 18,
  years_active: 12,
}

export const MOCK_TESTIMONIALS = [
  {
    id: 1,
    customer_name: 'Alhaji Musa Ibrahim',
    review: 'I bought my Range Rover from Sarkin Mota and the experience was flawless. The car was exactly as described. Nationwide delivery in 3 days!',
    rating: 5,
    car_bought: 'Range Rover Autobiography 2020',
    city: 'Kano',
  },
  {
    id: 2,
    customer_name: 'Mrs. Chidinma Okafor',
    review: 'Very professional and transparent. No hidden charges. My Mercedes GLE arrived spotless. My Bratha truly delivers!',
    rating: 5,
    car_bought: 'Mercedes-Benz GLE 2021',
    city: 'Lagos',
  },
  {
    id: 3,
    customer_name: 'Engr. Babatunde Adeyemi',
    review: 'Third car I am buying from Sarkin Mota. The trust is there. Best car dealer in Nigeria hands down.',
    rating: 5,
    car_bought: 'Lexus LX 570 2019',
    city: 'Abuja',
  },
]