# Generated by Django 5.1.9 on 2026-03-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('url', models.URLField(blank=True, help_text='External image URL (use if not uploading)')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('cars', 'Cars'), ('showroom', 'Showroom'), ('dr-aliyu', 'Dr. Aliyu')], default='cars', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
