# Generated by Django 5.1.9 on 2026-03-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_deal_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
